name: cron-job

on:
  schedule:
    - cron: "50 5 * * *"

permissions:
  contents: write
  packages: read

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      GITHUB_REPO_URL: https://${{github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
      GITHUB_USERNAME: ${{ github.actor }}
      GITHUB_EMAIL: ${{ vars.EMAIL }}
      COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
    container:
      image: ghcr.io/${{ github.repository }}:latest
    steps:
      - name: Run
        working-directory: /app
        run: uv run python init.py
