name: test-job

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          ls -la
          git status
          git add .
          git commit -m "Update"
  docker:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:latest
    steps:
      - uses: actions/checkout@v4
      - name: Run
        run: ls -la
