name: test-job

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          ls -la
          git status
          git log
  docker:
    runs-on: ubuntu-latest
    env:
      GITHUB_REPO_URL: https://${{github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
      GITHUB_USERNAME: ${{ github.actor }}
      GITHUB_EMAIL: ${{ vars.EMAIL }}
    container:
      image: ghcr.io/${{ github.repository }}:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run
        run: python init.py
